### PR TITLE
Add OwlClock extension to store

### PR DESCRIPTION
**Pull request by vijexa**
Make sure that your submission has the following:

- [x] A link to the raw github markdown file with a YAML front matter definition containing:
  - [x] The title of your extension
  - [x] A description of your extension
  - [x] The author
  - [x] A hero image
  - [x] An icon
  - [x] Tags (these will help with your extension's discoverability)
  - [x] A link to your extensions manifest

Please, go through these steps before you submit a PR.

- [x] You have done your changes in a separate branch.

- [x] You have a descriptive commit message with a short title (first line).

- [x] You have only one commit (if not, squash them into one commit).

- [x] Your pull request MUST target the `main` branch on this repository.

- [x] Your pull request puts your extensions details as the last entry in the extensions.json file

### CODE REVIEW

**Comment by nthouliss** [comment]
Thanks for your patience, it was the holidays before we knew it!

The tags must be in lower-case. So you need to change "Tool" to "tool". 

Just as a heads up, your count script gets blocked by uBlock origin (ad-blocker). I'm also not sure on your History size setting, maybe it's really subtle but doesn't seem to affect the history size (but maybe I'm also using it wrong). Those things don't affect your submission, just thought you'd like to know.

**Comment by vijexa** [comment]
Hi!

Thanks, changed `tool` tag to lowercase. Also rebased this PR and put owlclock into the end of the list again.

>Just as a heads up, your count script gets blocked by uBlock origin (ad-blocker). 

That's good! If people want to block counters they should be able to do so, the purpose of the counter was just to know if anyone uses the extension (and to feel good if they do!). It also had a side-effect of me realizing that a lot of people use OBR on small phones, so I plan to improve the responsiveness a bit.

>  I'm also not sure on your History size setting, maybe it's really subtle but doesn't seem to affect the history size (but maybe I'm also using it wrong)

Yeah, it's not really obvious, and tbh probably unneeded, maybe I'll remove this setting. It impacts how much of these "bubbles" can be displayed in the lower part of action window, but if you reduce the history size it'll only update after you change time using the hours/minutes buttons... Not a great UX, will do something about it later.

**Comment by nthouliss** [comment]
No worries then, thanks for those changes (and the rebase).

**Review by nthouliss — APPROVED** [review]

**Comment by vijexa** [comment]
Hi @nthouliss, thanks for merging!
I've noticed that the extension doesn't appear in the store. Does it just take some time to update, or could there be something wrong in my store.md? I've compared it with other extensions and didn't find any difference except for the fact that I used an emoji in the title. Could this be a problem?

**Comment by nthouliss** [comment]
@vijexa it should be resolved now, I think something went weird with the deployment :)

**Pull request merged**
