### PR TITLE
Add Dynamic Fog

### PR DESCRIPTION
**Pull request by ArmindoFlores**
Make sure that your submission has the following:

- [x] A link to the raw github markdown file with a YAML front matter definition containing:
  - [x] The title of your extension
  - [x] A description of your extension
  - [x] The author
  - [x] A hero image
  - [x] An icon
  - [x] Tags (these will help with your extension's discoverability)
  - [x] A link to your extensions manifest

Please, go through these steps before you submit a PR.

- [x] You have done your changes in a separate branch.

- [x] You have a descriptive commit message with a short title (first line).

- [x] You have only one commit (if not, squash them into one commit).

- [x] Your pull request MUST target the `main` branch on this repository.

- [x] Your pull request puts your extensions details as the last entry in the extensions.json file

### CODE REVIEW

**Comment by mitchemmc** [comment]
This is looking good.
I noticed that whenever a drawing is finished there is an empty selection made.

This is because technically the `onToolClick` function isn't asynchronous and expects a boolean return value.
Since a `Promise` is truthy then it the SDK is calling select for you because it thinks that's what you want.

I can see how this can be confusing so I'll try and update the SDK so the `onToolClick` function excepts a return value of a `Promse`. This should hopefully fix this issue.

**Comment by mitchemmc** [comment]
Ok if you update to SDK `v1.3.7` this should fix issues with the drawing tools selecting items https://github.com/owlbear-rodeo/sdk/releases/tag/v1.3.7

If you want we also now have key event handlers for tool modes here https://docs.owlbear.rodeo/extensions/apis/tool#toolmode

**Comment by ArmindoFlores** [comment]
> Ok if you update to SDK `v1.3.7` this should fix issues with the drawing tools selecting items https://github.com/owlbear-rodeo/sdk/releases/tag/v1.3.7
> 
> If you want we also now have key event handlers for tool modes here https://docs.owlbear.rodeo/extensions/apis/tool#toolmode

I've added this as well as updated the SDK version.

**Comment by mitchemmc** [comment]
Looks good to me.

There's a small thing where the CSS for the Action Popover will use the users dark mode preference.
This is the default for Vite apps but it will mean the popover will be white on some users computers. It's cool if you want to keep this but it might be unexpected behaviour for users as currently OBR is mostly a dark interface.

This is a small thing though so I'm happy to accept this now.

**Review by mitchemmc — APPROVED** [review]

**Comment by nthouliss** [comment]
Hi @ArmindoFlores 

We have a migration taking place to move our domain from owlbear.app to owlbear.rodeo. 

If you rely on a CORS Access-Control-Allow-Origin policy then please change this to either `*` or `https://www.owlbear.rodeo`.

Apologies for the late notice and we'll do our best to inform you once migration is complete.

**Pull request merged**
