### PR TITLE
Add Tabletop Card Deck

### PR DESCRIPTION
**Pull request by mawburn**
Make sure that your submission has the following:

- [x] A link to the raw github markdown file with a YAML front matter definition containing:
- [x] The title of your extension
- [x] A description of your extension
- [x] The author
- [x] A hero image
- [x] An icon
- [x] Tags (these will help with your extension's discoverability)
- [x] A link to your extensions manifest

Please, go through these steps before you submit a PR.

- [x] You have done your changes in a separate branch.
- [x] You have a descriptive commit message with a short title (first line).
- [x] You have only one commit (if not, squash them into one commit).
- [x] Your pull request MUST target the `main` branch on this repository.
- [x] Your pull request puts your extensions details as the last entry in the extensions.json file

https://github.com/owlbear-rodeo/extensions/assets/2829924/e55520f5-f2ef-41b2-ae34-11500a822064

### CODE REVIEW

**Comment by mitchemmc** [comment]
Just getting to this now.
The image in the store page `https://mawburn.github.io/obr-cards/Example.webp` seems to be invalid

**Comment by mitchemmc** [comment]
Also make sure your tags are one of the available tags here https://github.com/owlbear-rodeo/extensions/blob/main/tags.json

**Comment by mawburn** [comment]
> Just getting to this now.
> The image in the store page https://mawburn.github.io/obr-cards/Example.webp seems to be invalid

I didn't see this listed anywhere. Is this a standard you put forth? It's not in my code. I called it Demo but I can change it.

**Comment by mawburn** [comment]
On second thought. I'm not going to keep this up to date. After seeing total radio silence for 3-4months, I don't feel like this is a project worth contributing to.

Best of luck.

**Comment by mitchemmc** [comment]
Just to rebut this utter nonsense if someone else comes to this PR.
I don't treat GitHub like a social media app that needs constant updates.
If you wanted an update you could have asked and I would have happily gave you one.
As many have done on our Discord and have gotten an answer within a day of asking.

I could give you the reasons for the delay but I'm guessing you wouldn't really care anyway.

**Pull request closed without merging**
