### PR TITLE
Bones! to OBR Store

### PR DESCRIPTION
**Pull request by ManuelLovell**
Make sure that your submission has the following:

- [x] A link to the raw github markdown file with a YAML front matter definition containing:
  - [x] The title of your extension
  - [x] A description of your extension
  - [x] The author
  - [x] A hero image
  - [x] An icon
  - [x] Tags (these will help with your extension's discoverability)
  - [x] A link to your extensions manifest

Please, go through these steps before you submit a PR.

- [x] You have done your changes in a separate branch.

- [x] You have a descriptive commit message with a short title (first line).

- [x] You have only one commit (if not, squash them into one commit).

- [x] Your pull request MUST target the `main` branch on this repository.

- [x] Your pull request puts your extensions details as the last entry in the extensions.json file

### CODE REVIEW

**Comment by nthouliss** [comment]
Your manifest and store file is fine but there's an issue with the viewport width being called every second. I'm not sure why you need to call it this frequently, if you just need to pin it to the corner than the OBR dice popover code might help since that's always pinned to the bottom right. 

The dice popover that you have in the bottom will break if it is open, dice are chosen and then the screen is resized. You can recover from that by rolling the dice but it's probably best to handle this by resetting the selection (i.e. by putting back to the starting state).

**Comment by ManuelLovell** [comment]
> Your manifest and store file is fine but there's an issue with the viewport width being called every second. I'm not sure why you need to call it this frequently, if you just need to pin it to the corner than the OBR dice popover code might help since that's always pinned to the bottom right.
> 

So, this was a band-aid step since there isn't a Viewport.OnChange available.  If the Dice-UI is in a small window, and then someone expands their window - the UI-Button will sit in the middle of the screen.  (The popover code is only going to be called when they click the button, which means it would only be reset when interacted with. Which feels kind of weird.) There doesn't appear to be a way to re-position it reactively.  Any ideas on this one?

> The dice popover that you have in the bottom will break if it is open, dice are chosen and then the screen is resized. You can recover from that by rolling the dice but it's probably best to handle this by resetting the selection (i.e. by putting back to the starting state).
> 

Noted, haven't thought to try that scenario.  I'll figure a solution to this one pending the resolution to the repositioning issue -since that's the root cause.

> Edit: I also want to check but is a scene being open a requirement for this extension? It doesn't work when the Scene is closed but if this is intended, it would be good to give some feedback to the user.

It did not click to me that the Viewport was scene dependent (Though I see it now in the docs.)  I was thinking only things in the OBR.Scene tree were.  I suppose I could disable it, but I'll see if there are any other avenues in terms of getting the window size.

**Comment by mitchemmc** [comment]
If you wish to create a popover at a different location in the viewport you should use the anchors without an `anchorElementId`. See how the our dice creates a popover in the bottom right here:
https://github.com/owlbear-rodeo/dice/blob/105f1718e07cefebb8a20f57058266d27888dafb/src/background.ts#L10

Since the SDK is asynchronous there isn't likely going to be an `onViewportChange` event added because it could lead to performance issues.

**Comment by ManuelLovell** [comment]
> If you wish to create a popover at a different location in the viewport you should use the anchors without an `anchorElementId`. See how the our dice creates a popover in the bottom right here: https://github.com/owlbear-rodeo/dice/blob/105f1718e07cefebb8a20f57058266d27888dafb/src/background.ts#L10
> 
> Since the SDK is asynchronous there isn't likely going to be an `onViewportChange` event added because it could lead to performance issues.

Gotcha.  Is there anything that I'm missing in terms of adjustments? While I can anchor it to the bottom-right without issue, from there the only customizations I can make are in the form of changing the margin threshold by a flat number for both X and Y.

In this particular instance, I'm really just trying to avoid overlapping the OBR Grid button - so I really just want to move up by 50 or so pixels.
Marginthreshold will throw the button over the dock. Thoughts?

**Comment by mitchemmc** [comment]
You would need to do a lot more to avoid overlapping the OBR UI.
On mobile the grid button get's merged into the dock which can change height.
So the solution here is probably to use the Action popover and allow the user to position it.
Action popovers will automatically flow around the UI

**Comment by ManuelLovell** [comment]
I've re-configured this for acceptance.

**Comment by ManuelLovell** [comment]
@mitchemmc Is there anything else I can do to move this for acceptance?

**Review by nthouliss — APPROVED** [review]

**Pull request merged**
