### PR TITLE
Add Hp Tracker Extension to extensions.json

### PR DESCRIPTION
**Pull request by kamejosh**
Make sure that your submission has the following:

- [x] A link to the raw github markdown file with a YAML front matter definition containing:
  - [x] The title of your extension
  - [x] A description of your extension
  - [x] The author
  - [x] A hero image
  - [x] An icon
  - [x] Tags (these will help with your extension's discoverability)
  - [x] A link to your extensions manifest

Please, go through these steps before you submit a PR.

- [x] You have done your changes in a separate branch.

- [x] You have a descriptive commit message with a short title (first line).

- [x] You have only one commit (if not, squash them into one commit).

- [x] Your pull request MUST target the `main` branch on this repository.

- [x] Your pull request puts your extensions details as the last entry in the extensions.json file

### CODE REVIEW

**Review by mitchemmc — APPROVED** [review]

**Comment by mitchemmc** [comment]
I did a bit more of a deep dive on this after a report of some issues.
It looks like you're interacting with the scene once the room is ready.
https://github.com/kamejosh/owlbear-hp-tracker/blob/master/src/obr/init.ts#L25
There was a bug in the SDK that allowed this but it is actually undefined behaviour.

After the room loads both the extensions and the scene will start loading at the same time in parallel.
If the extension loads after the scene then everything would be fine.
The network calls in that case would look something like this:
```
|--Room Loads--|
               |---Scene Loads---|
               |---Extension Loads---|
```

Because both are asynchronous if the extension was to load before the scene then calling a Scene API will result in data corruption.
```
|--Room Loads--|
               |------Scene Loads------|
               |--Extension Loads--|
```

To prevent the scene from being corrupted we now properly throw an error when trying to interact with the scene before it is ready.

So now in order to run your initialisation functions that interact with the scene you will need to make sure the scene is ready.
https://docs.owlbear.rodeo/extensions/apis/scene/#onreadychange

**Comment by kamejosh** [comment]
Thank you for letting me know, will be fixed in just a moment

**Comment by nthouliss** [comment]
Hi @kamejosh 

We have a migration taking place to move our domain from owlbear.app to owlbear.rodeo. 

If you rely on a CORS Access-Control-Allow-Origin policy then please change this to either `*` or `https://www.owlbear.rodeo`.

Apologies for the late notice and we'll do our best to inform you once migration is complete.

**Comment by kamejosh** [comment]
Thank you, I just change might ACAO Header, everythings working now.

**Pull request merged**
