### PR TITLE
Add C&S 5e AP Tracker to extensions list

### PR DESCRIPTION
**Pull request by pumbers**
Make sure that your submission has the following:

- [X] A link to the raw github markdown file with a YAML front matter definition containing:
  - [X] The title of your extension
  - [X] A description of your extension
  - [X] The author
  - [X] A hero image
  - [X] An icon
  - [X] Tags (these will help with your extension's discoverability)
  - [X] A link to your extensions manifest

Please, go through these steps before you submit a PR.

- [X] You have done your changes in a separate branch.

- [X] You have a descriptive commit message with a short title (first line).

- [X] You have only one commit (if not, squash them into one commit).

- [X] Your pull request MUST target the `main` branch on this repository.

- [X] Your pull request puts your extensions details as the last entry in the extensions.json file

**IMPORTANT:** Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.

### CODE REVIEW

**Comment by mitchemmc** [comment]
Looking good, I noticed that there was a call to `getItemAttachments` on every item change but I couldn't figure out the what the reason for this was when testing the extension.
The `onChange` handler actually passes in all the items (including attachments) not just the items that have changed. So calling `getItemAttachments` shouldn't be needed.

I also noticed in your `store.md` that the image `src` urls are relative. At the moment our store works by statically generating a html page from your markdown. So image urls need to be absolute links as the page is hosted on our site. I'll make a note to update our documentation to mention this.

**Comment by pumbers** [comment]
The updates you suggested have been made & tested. Thanks for the pointers.

**Review by mitchemmc — APPROVED** [review]
lgtm

**Comment by nthouliss** [comment]
Hi @pumbers 

We have a migration taking place to move our domain from owlbear.app to owlbear.rodeo. 

If you rely on a CORS Access-Control-Allow-Origin policy then please change this to either `*` or `https://www.owlbear.rodeo`.

Apologies for the late notice and we'll do our best to inform you once migration is complete.

**Pull request merged**
