### PR TITLE
Add Character Distances

### PR DESCRIPTION
**Pull request by Croebh**
Add Character Distances

Make sure that your submission has the following:

- [x] A link to the raw github markdown file with a YAML front matter definition containing:
  - [x] The title of your extension
  - [x] A description of your extension
  - [x] The author
  - [x] A hero image
  - [x] An icon
  - [x] Tags (these will help with your extension's discoverability)
  - [x] A link to your extensions manifest

Please, go through these steps before you submit a PR.

- [x] You have done your changes in a separate branch.

- [x] You have a descriptive commit message with a short title (first line).

- [x] You have only one commit (if not, squash them into one commit).

- [x] Your pull request MUST target the `main` branch on this repository.

- [x] Your pull request puts your extensions details as the last entry in the extensions.json file

### CODE REVIEW

**Comment by mitchemmc** [comment]
The tags present in the store page are invalid.
Make sure you use the tags that exist in this file https://github.com/owlbear-rodeo/extensions/blob/main/tags.json

**Comment by Croebh** [comment]
Fixed the tags, not sure how I missed the documentation linking to them haha, thank you.

**Review by mitchemmc — APPROVED** [review]

**Comment by nthouliss** [comment]
Hi @Croebh 

We have a migration taking place to move our domain from owlbear.app to owlbear.rodeo. 

If you rely on a CORS Access-Control-Allow-Origin policy then please change this to either `*` or `https://www.owlbear.rodeo`.

Apologies for the late notice and we'll do our best to inform you once migration is complete.

**Comment by Croebh** [comment]
Thanks for the heads up, I've made the change!

**Pull request merged**
