### PR TITLE
Add Token Auras

### PR DESCRIPTION
**Pull request by SeamusFinlayson**
Make sure that your submission has the following:

- [x] A link to the raw github markdown file with a YAML front matter definition containing:
  - [x] The title of your extension
  - [x] A description of your extension
  - [x] The author
  - [x] A hero image
  - [x] An icon
  - [x] Tags (these will help with your extension's discoverability)
  - [x] A link to your extensions manifest

Please, go through these steps before you submit a PR.

- [x] You have done your changes in a separate branch.

- [x] You have a descriptive commit message with a short title (first line).

- [x] You have only one commit (if not, squash them into one commit).

- [x] Your pull request MUST target the `main` branch on this repository.

- [x] Your pull request puts your extensions details as the last entry in the extensions.json file

### CODE REVIEW

**Comment by Several-Record7234** [comment]
Validation script and image URLs check out fine. Extension functionality and API usage not checked.

**Review by nthouliss — CHANGES_REQUESTED** [review]
Just a couple of thing:
- Could you make the homepage_url in the manifest go to the extension github instead?
- The aura doesn't take image alignment into account, the aura isn't centred if the image alignment isn't in the top left

**Comment by SeamusFinlayson** [comment]
- Oops, forgot to add the repo
- Alignment should be accounted for, as well as rotation and scale

**Review by nthouliss — APPROVED** [review]
Looks good! 

I think you could make this a little more mobile-friendly by changing the UI to take a little more horizontal space rather than vertical but that's just general feedback :)

**Pull request merged**
