### PR TITLE
Added Sheet From Beyond

### PR DESCRIPTION
**Pull request by alvarocavalcanti**
Make sure that your submission has the following:

- [x] A link to the raw github markdown file with a YAML front matter definition containing:
  - [x] The title of your extension
  - [x] A description of your extension
  - [x] The author
  - [x] A hero image
  - [x] An icon
  - [x] Tags (these will help with your extension's discoverability)
  - [x] A link to your extensions manifest

Please, go through these steps before you submit a PR.

- [x] You have done your changes in a separate branch.

- [x] You have a descriptive commit message with a short title (first line).

- [x] You have only one commit (if not, squash them into one commit).

- [x] Your pull request MUST target the `main` branch on this repository.

- [x] Your pull request puts your extensions details as the last entry in the extensions.json file

### CODE REVIEW

**Comment by nthouliss** [comment]
The tag sheet is not supported. These are our supported tag with the exception of `built-by-owlbear` in your case. 

https://github.com/owlbear-rodeo/extensions/blob/main/tags.json

**Comment by alvarocavalcanti** [comment]
> The tag `sheet` is not supported. These are our supported tag with the exception of `built-by-owlbear` in your case.
> 
> https://github.com/owlbear-rodeo/extensions/blob/main/tags.json

Fixed!

**Comment by Several-Record7234** [comment]
Validation script and image URLs check out fine.

**Comment by Several-Record7234** [comment]
(As far as I can tell, all 13 of the task prerequisites for a PR have now been met, but @alvarocavalcanti hasn't yet edited his initial comment to reflect that.)

**Comment by alvarocavalcanti** [comment]
> (As far as I can tell, all 13 of the task prerequisites for a PR have now been met, but @alvarocavalcanti hasn't yet edited his initial comment to reflect that.)

All boxes have been ticked now, and the conflicts addressed. Thanks!

**Comment by nthouliss** [comment]
Thanks for your patience @alvarocavalcanti just a few things.

1. If I hit cancel when adding a URL to the adding sheet alert message it throws an error message to the UI. I don't think this is needed when choosing to cancel.
2. I'd probably specifically mention DnDBeyond not working in Popover mode (or just throw a message in the iframe if someone tries to open a dndbeyond sheet in the popover). You can't log in since they use third party auth like Apple and Google and the iframe just fails. You mention that in this scenario it offers to open in a new tab but I didn't have this experience. 
3. There's an issue with loading your icon at this url: https://sheet-from-beyond.vercel.app/img/sheet-icon.svg

**Comment by nthouliss** [comment]
> > (As far as I can tell, all 13 of the task prerequisites for a PR have now been met, but @alvarocavalcanti hasn't yet edited his initial comment to reflect that.)
> 
> All boxes have been ticked now, and the conflicts addressed. Thanks!

I'm happy with this and I'm ready to give it a merge but your commits need to be squashed to one commit. If you're not familiar with squashing commits I'd recommend using GitHub Desktop to do so and then doing a force push to your branch. 

https://docs.github.com/en/desktop/managing-commits/squashing-commits-in-github-desktop

**Comment by alvarocavalcanti** [comment]
> Thanks for your patience @alvarocavalcanti just a few things.
> 
>     1. If I hit cancel when adding a URL to the adding sheet alert message it throws an error message to the UI. I don't think this is needed when choosing to cancel.
> 
>     2. I'd probably specifically mention DnDBeyond not working in Popover mode (or just throw a message in the iframe if someone tries to open a dndbeyond sheet in the popover). You can't log in since they use third party auth like Apple and Google and the iframe just fails. You mention that in this scenario it offers to open in a new tab but I didn't have this experience.
> 
>     3. There's an issue with loading your icon at this url: https://sheet-from-beyond.vercel.app/img/sheet-icon.svg

@nthouliss 

1. I've removed the error message, now the code will just exit without adding anything to the sheet
2. I've tweaked the text, and I tested it with DDB, if you mark the sheet as public you don't need to login, just accept the cookies and it will work just fine in the popover
3. The URL has been updated

**Pull request closed without merging**
