### PR TITLE
Add Last Fable and Ultimate Story Extensions for Fabula Ultima

### PR DESCRIPTION
**Pull request by greg-argulla**
Make sure that your submission has the following:

- [x] A link to the raw github markdown file with a YAML front matter definition containing:
  - [x] The title of your extension
  - [x] A description of your extension
  - [x] The author
  - [x] A hero image
  - [x] An icon
  - [x] Tags (these will help with your extension's discoverability)
  - [x] A link to your extensions manifest

Please, go through these steps before you submit a PR.

- [x] You have done your changes in a separate branch.

- [x] You have a descriptive commit message with a short title (first line).

- [x] You have only one commit (if not, squash them into one commit).

- [x] Your pull request MUST target the `main` branch on this repository.

- [x] Your pull request puts your extensions details as the last entry in the extensions.json file

### CODE REVIEW

**Comment by mitchemmc** [comment]
Looking good I can see most edge cases are covered with local storage and scene loading.
The only issue I see right now is with text legibility.
I had no issues with the retina screen for my Macbook but when viewing on an external monitor with a 1x pixel scale it was very hard to read the text.
Here is a typescale guide from google https://m2.material.io/design/typography/the-type-system.html#type-scale
unnamed (1)

Here buttons are recommended to have a font-size of 14px but I believe the extensions use a range of 8-10px.
The text legibility issue also might be caused by the text-shadow outline which on a non-retina screen can lead to the outline to become pixelated.

**Comment by greg-argulla** [comment]
Though I cannot increase the button's fontsize to 14 due to space limitation, I did increase all button fontsize to be at least 10 or higher. I also switched the background to something darker. Hopefully this is able to retify the issue.

image

**Comment by mitchemmc** [comment]
The contrast definitely helps with accessibility.
It looks like this extension also doesn't support smaller screen sizes.
Around 50% of our users are on mobile so I'd like to see either support a more responsive design or support for scrollbars.
For example here is what it looks like on a smaller iPhone:
image

**Comment by greg-argulla** [comment]
I found a way to just scale everything up to 1.1x so I pushed an update for it. For mobile I'll see what I can do.

**Comment by greg-argulla** [comment]
Hello, I manage to add a scroll feature for mobile view if that would suffice. Let me know if you need anything else.

**Review by mitchemmc — APPROVED** [review]

**Comment by mitchemmc** [comment]
Hey sorry it took so long, we had to deal with a bunch of things behind the scenes.
It should now be merged.

**Pull request merged**
