### PR TITLE
Added: Map Location Keys

### PR DESCRIPTION
**Pull request by alvarocavalcanti**
Make sure that your submission has the following:

- [x] A link to the raw github markdown file with a YAML front matter definition containing:
  - [x] The title of your extension
  - [x] A description of your extension
  - [x] The author
  - [x] A hero image
  - [x] An icon
  - [x] Tags (these will help with your extension's discoverability)
  - [x] A link to your extensions manifest

Please, go through these steps before you submit a PR.

- [x] You have done your changes in a separate branch.

- [x] You have a descriptive commit message with a short title (first line).

- [x] You have only one commit (if not, squash them into one commit).

- [x] Your pull request MUST target the `main` branch on this repository.

- [x] Your pull request puts your extensions details as the last entry in the extensions.json file

### CODE REVIEW

**Comment by nthouliss** [comment]
These are our supported tags which can be used with the exception of `built-by-owlbear` in your case. 

https://github.com/owlbear-rodeo/extensions/blob/main/tags.json

**Comment by alvarocavalcanti** [comment]
> These are our supported tags which can be used with the exception of `built-by-owlbear` in your case.
> 
> https://github.com/owlbear-rodeo/extensions/blob/main/tags.json

Fixed!

**Comment by nthouliss** [comment]
Cool! Thank you, I'd probably put your extension under the `tool` tag and remove the `other` tag but `other` is acceptable if you want. 

The help sections are great, I would probably add a blur on your room link in your help video in the extension (the URL is visible in the chrome browser that you screen recorded) just to prevent any possible spam. You should be able to do this in YouTube so you don't have to re-upload the video. Deleting the room is also an option. 

Once you let me know that the room has been deleted or the video edited then I'm happy to approve for the store :)

**Comment by alvarocavalcanti** [comment]
Thanks for the feedback. I've switched to the `tool` tag as recommended and also added a blur to the URLs in both videos, but it might take a while to be fully applied, thanks for the tip!

**Comment by nthouliss** [comment]
@alvarocavalcanti This should be ready to accept, could you please squash your commits into one?

**Comment by alvarocavalcanti** [comment]
Messed up with the rebase, I will close this and open a new one.

**Comment by alvarocavalcanti** [comment]
Created #67 as a replacement

**Pull request closed without merging**
