### PR TITLE
Rumble Chat extension to OBR Store

### PR DESCRIPTION
**Pull request by ManuelLovell**
Make sure that your submission has the following:

- [✅] A link to the raw github markdown file with a YAML front matter definition containing:
  - [✅] The title of your extension
  - [✅] A description of your extension
  - [✅] The author
  - [✅] A hero image
  - [✅] An icon
  - [✅] Tags (these will help with your extension's discoverability)
  - [✅] A link to your extensions manifest

Please, go through these steps before you submit a PR.

- [✅] You have done your changes in a separate branch.

- [✅] You have a descriptive commit message with a short title (first line).

- [✅] You have only one commit (if not, squash them into one commit).

- [✅] Your pull request MUST target the `main` branch on this repository.

- [✅] Your pull request puts your extensions details as the last entry in the extensions.json file

### CODE REVIEW

**Comment by mitchemmc** [comment]
This is looking good.
As this extension uses the scene metadata to function it will not work when no scene is open.
This is ok but currently there is no error message shown to the user when this happens.
I would like to see either the app detect when no scene is open and prevent users from sending a message or show an error message when a message can't be sent.

I've also noticed that the dice roll buttons will be cut off on smaller screen sizes.
I would like to see a more responsive design so users on mobile can use the full functionality.

**Comment by ManuelLovell** [comment]
I'll make the changes for the no-scene issue;
Curiously, what screen size were you testing with for mobile? I had made upsets for smaller screen sizes a few days ago and am curious what size this is still an issue on.
image

**Comment by mitchemmc** [comment]
Here's what my exension looks like with an iPhone SE test resolution.
image

**Comment by mitchemmc** [comment]
Ok I had to clear my cache but here's what it looks like with the updated icons
image

**Comment by ManuelLovell** [comment]
Appreciate the feedback, pushed an update to be more responsive to a variety of widths and not just one set size.

**Review by mitchemmc — APPROVED** [review]

**Pull request merged**
