### PR TITLE
add dashboard-maker to extensions.json

### PR DESCRIPTION
**Pull request by RobertTate**
Make sure that your submission has the following:

- [x] A link to the raw github markdown file with a YAML front matter definition containing:
  - [x] The title of your extension
  - [x] A description of your extension
  - [x] The author
  - [x] A hero image
  - [x] An icon
  - [x] Tags (these will help with your extension's discoverability)
  - [x] A link to your extensions manifest

Please, go through these steps before you submit a PR.

- [x] You have done your changes in a separate branch.

- [x] You have a descriptive commit message with a short title (first line).

- [x] You have only one commit (if not, squash them into one commit).

- [x] Your pull request MUST target the `main` branch on this repository.

- [x] Your pull request puts your extensions details as the last entry in the extensions.json file

### CODE REVIEW

**Comment by RobertTate** [comment]
@nthouliss  I went ahead and removed the "tool" tag from my `store.md` file, and make my best attempt to add a gif as the hero image, per your recommendation. 

Let me know if any other changes are needed!

**Comment by RobertTate** [comment]
Actually, I do want to check one thing tomorrow...I want to make sure that my use of localforage wouldn't interfere with any other use of localforage from any other extension. I need to namespace the db store it create for my app, I think.

Let me play with that before you merge, if you don't mind. I should have it figured out sometime tomorrow.

**Comment by RobertTate** [comment]
@nthouliss ok, fixed. Ready to go when you are 😄

**Comment by RobertTate** [comment]
@nthouliss just checking back on this PR. Is there anything else needed?

**Review by nthouliss — APPROVED** [review]

**Comment by RobertTate** [comment]
@nthouliss I'm realizing after merging that the image references in my `store.md` file were using relative paths to the images. It seems I need to use the absolute paths of the images that were already uploaded.

I've already fixed it on my end. Will that just auto-update after some time on the owlbear page?

This page here: https://extensions.owlbear.rodeo/dashboard-maker

**Comment by nthouliss** [comment]
@RobertTate I jumped on to let you know, I should have been more thorough when checking the images. I've triggered a redeployment now and it should be fixed on the extension store when it's completed

**Comment by RobertTate** [comment]
Thanks!

**Pull request merged**
