### PR TITLE
add: Decked! to OBR Store

### PR DESCRIPTION
**Pull request by ManuelLovell**
Make sure that your submission has the following:

- [x] A link to the raw github markdown file with a YAML front matter definition containing:
  - [x] The title of your extension
  - [x] A description of your extension
  - [x] The author
  - [x] A hero image
  - [x] An icon
  - [x] Tags (these will help with your extension's discoverability)
  - [x] A link to your extensions manifest

Please, go through these steps before you submit a PR.

- [x] You have done your changes in a separate branch.

- [x] You have a descriptive commit message with a short title (first line).

- [x] You have only one commit (if not, squash them into one commit).

- [x] Your pull request MUST target the `main` branch on this repository.

- [x] Your pull request puts your extensions details as the last entry in the extensions.json file

### CODE REVIEW

**Comment by Several-Record7234** [comment]
Hey, there may be a few issues with your store.md contents:

1. https://battle-system.com/owlbear/decked-docs/preview.png doesn't work in-browser for me, I'm getting a 404 error
2. https://battle-system.com/owlbear/chronicle-docs/logo.png also doesn't work in-browser for me, another 404 error
3. in the Support section, the Discord link is an older one that has now been removed, please use this official link instead `https://discord.gg/u5RYMkV98s`

Thanks!

Andrew.

**Comment by ManuelLovell** [comment]
> Hey, there may be a few issues with your store.md contents:
> 
> 1. https://battle-system.com/owlbear/decked-docs/preview.png doesn't work in-browser for me, I'm getting a 404 error
> 2. https://battle-system.com/owlbear/chronicle-docs/logo.png also doesn't work in-browser for me, another 404 error
> 3. in the Support section, the Discord link is an older one that has now been removed, please use this official link instead `https://discord.gg/u5RYMkV98s`
> 
> Thanks!
> 
> Andrew.

Noted - the preview image was a WEBP, not PNG - so I updated the link.
The logo image (I assume you meant for decked) was missing, so it's been added.
I updated the Discord link for every readme file.

Thanks for the check-in!

**Comment by Several-Record7234** [comment]
Yep, noob error from me as I copied and pasted a prior message! 

> Noted - the preview image was a WEBP, not PNG - so I updated the link. The logo image (I assume you meant for decked) was missing, so it's been added. I updated the Discord link for every readme file.
> 
> Thanks for the check-in!

**Comment by Several-Record7234** [comment]
Validation script and image URLs check out fine. Extension functionality and API usage not checked.

**Comment by nthouliss** [comment]
I'd recommend changing the tag to `other`

**Comment by ManuelLovell** [comment]
> I'd recommend changing the tag to `other`

Updated also.

**Review by nthouliss — APPROVED** [review]

**Pull request merged**
