### PR TITLE
Journal! to the Owlbear Store

### PR DESCRIPTION
**Pull request by ManuelLovell**
Make sure that your submission has the following:

- [x] A link to the raw github markdown file with a YAML front matter definition containing:
  - [x] The title of your extension
  - [x] A description of your extension
  - [x] The author
  - [x] A hero image
  - [x] An icon
  - [x] Tags (these will help with your extension's discoverability)
  - [x] A link to your extensions manifest

Please, go through these steps before you submit a PR.

- [x] You have done your changes in a separate branch.

- [x] You have a descriptive commit message with a short title (first line).

- [x] You have only one commit (if not, squash them into one commit).

- [x] Your pull request MUST target the `main` branch on this repository.

- [x] Your pull request puts your extensions details as the last entry in the extensions.json file

### CODE REVIEW

**Comment by nthouliss** [comment]
Heya!

Only feedback is that it seems like the notes shouldn't be viewable between rooms. At least that's the impression that I got from the information on the extension but I could load my page 1 notes in another room when I swapped rooms.

**Comment by ManuelLovell** [comment]
> Heya!
> 
> Only feedback is that it seems like the notes shouldn't be viewable between rooms. At least that's the impression that I got from the information on the extension but I could load my page 1 notes in another room when I swapped rooms.

So this one was by design;
Since I can't save large amounts of text to the room-data, I have the text being saved locally.

Going this route, I opted for the GM to have several 'slots' that they can swap through, but whichever slot they were on last is what's keyed to the room (So you don't enter and have the wrong campaign's notes open by default.)
This also helps if they decide to nuke their room for whatever reason, they would still have the notes accessible without it being keyed to an old ID.
This also mimics the functionality I have if they decide to go the remote storage route.

**Comment by nthouliss** [comment]
> Going this route, I opted for the GM to have several 'slots' that they can swap through, but whichever slot they were on last is what's keyed to the room (So you don't enter and have the wrong campaign's notes open by default.)
This also helps if they decide to nuke their room for whatever reason, they would still have the notes accessible without it being keyed to an old ID.

Ah I see, I was confused by the Journal 3/25 changes that say:

> The GM has 5 slots to swap through if you're running different rooms. The slot you're using is saved to the room, so people won't see your other stuff by default.

Does this mean that when you enable it in a room for the first time that a user/GM should choose the note to open? It's always on page one and party by default but maybe it should be closed? People have extensions enabled in rooms when they shouldn't have so it's possible that a player could edit the notes of another campaign without the GM realising. This isn't something you need to implement or anything, just some thoughts I'm having.

**Review by nthouliss — APPROVED** [review]

**Comment by ManuelLovell** [comment]
> > Going this route, I opted for the GM to have several 'slots' that they can swap through, but whichever slot they were on last is what's keyed to the room (So you don't enter and have the wrong campaign's notes open by default.)
> > This also helps if they decide to nuke their room for whatever reason, they would still have the notes accessible without it being keyed to an old ID.
> 
> Ah I see, I was confused by the Journal 3/25 changes that say:
> 
> > The GM has 5 slots to swap through if you're running different rooms. The slot you're using is saved to the room, so people won't see your other stuff by default.
> 
> Does this mean that when you enable it in a room for the first time that a user/GM should choose the note to open? It's always on page one and party by default but maybe it should be closed? People have extensions enabled in rooms when they shouldn't have so it's possible that a player could edit the notes of another campaign without the GM realising. This isn't something you need to implement or anything, just some thoughts I'm having.

That's a fair thought.  In my head, a GM would like.. prepare.. and look at the things before they do stuff.  But realistically it won't always be the case.  I can/will add an 'opt-in' to start things for fresh rooms.  Thanks for looking things over!

**Pull request merged**
