### PR TITLE
Add phases automated to the store

### PR DESCRIPTION
**Pull request by SeamusFinlayson**
Make sure that your submission has the following:

- [x] A link to the raw github markdown file with a YAML front matter definition containing:
  - [x] The title of your extension
  - [x] A description of your extension
  - [x] The author
  - [x] A hero image
  - [x] An icon
  - [x] Tags (these will help with your extension's discoverability)
  - [x] A link to your extensions manifest

Please, go through these steps before you submit a PR.

- [x] You have done your changes in a separate branch.

- [x] You have a descriptive commit message with a short title (first line).

- [x] You have only one commit (if not, squash them into one commit).

- [x] Your pull request MUST target the `main` branch on this repository.

- [x] Your pull request puts your extensions details as the last entry in the extensions.json file

### CODE REVIEW

**Comment by Several-Record7234** [comment]
Hey, there's a minor issue with your store.md contents:

1. in the Support section, the Discord link is an older one that has now been removed, please use this official link instead `https://discord.gg/u5RYMkV98s`

Thanks!

Andrew.

**Comment by SeamusFinlayson** [comment]
Fixed!

**Comment by Several-Record7234** [comment]
Validation script and image URLs check out fine. Extension functionality and API usage not checked.

**Review by nthouliss — APPROVED** [review]
LGTM!

I will say I think the check boxes are confusing. I think it would be more valuable to have a selectable dropdown with the options and then the user can select a trashcan icon to delete the property to remove it, it prevents the user from just toggling them all the time and ruining the automation.

**Pull request merged**
