### PR TITLE
Add Segmentable Ruler

### PR DESCRIPTION
**Pull request by SeamusFinlayson**
Make sure that your submission has the following:

- [X] A link to the raw github markdown file with a YAML front matter definition containing:
  - [X] The title of your extension
  - [X] A description of your extension
  - [X] The author
  - [X] A hero image
  - [X] An icon
  - [X] Tags (these will help with your extension's discoverability)
  - [X] A link to your extensions manifest

Please, go through these steps before you submit a PR.

- [X] You have done your changes in a separate branch.

- [X] You have a descriptive commit message with a short title (first line).

- [X] You have only one commit (if not, squash them into one commit).

- [X] Your pull request MUST target the `main` branch on this repository.

- [X] Your pull request puts your extensions details as the last entry in the extensions.json file

### CODE REVIEW

**Comment by Several-Record7234** [comment]
Hey, there's a minor issue with your store.md contents:

1. in the Support section, the Discord link is an older one that has now been removed, please use this official link instead `https://discord.gg/u5RYMkV98s`

Thanks!

Andrew.

**Comment by SeamusFinlayson** [comment]
Fixed!

**Comment by Several-Record7234** [comment]
Validation script and image URLs check out fine. Extension functionality and API usage not checked.

**Comment by Several-Record7234** [comment]
Validation script and image URLs check out fine. Extension functionality and API usage not checked.

**Review by nthouliss — APPROVED** [review]
Thanks for the patience @SeamusFinlayson looks all good. The only issue I had was using the escape key after hitting enter to make a ruler permanent, the token wouldn't return to the original position. It could be that I was misinterpreting the instructions though

**Comment by SeamusFinlayson** [comment]
That only works while you're still measuring, I think I can make that clearer by switching the order of bullet points in the documentation. The finishing a measurement options are mutually exclusive.

**Pull request merged**
