### PR TITLE
Adds Dragonbane Initiative

### PR DESCRIPTION
**Pull request by nboughton**
Make sure that your submission has the following:

- [x] A link to the raw github markdown file with a YAML front matter definition containing:
  - [x] The title of your extension
  - [x] A description of your extension
  - [x] The author
  - [x] A hero image
  - [x] An icon
  - [x] Tags (these will help with your extension's discoverability)
  - [x] A link to your extensions manifest

Please, go through these steps before you submit a PR.

- [x] You have done your changes in a separate branch.

- [x] You have a descriptive commit message with a short title (first line).

- [x] You have only one commit (if not, squash them into one commit).

- [x] Your pull request MUST target the `main` branch on this repository.

- [x] Your pull request puts your extensions details as the last entry in the extensions.json file

### CODE REVIEW

**Comment by nthouliss** [comment]
Hi @nboughton! Thanks for your patience I know it's been a while since you submitted. 

I'm having some trouble with your links. The images and the learn more page resolves to a 404. 

There's also a small bug with initiative appearing between refreshes. If I have some tokens, add them to initiative, draw initiative and then refresh the page the initiative won't appear. I can see that the extension does remember what tokens had initiative because if I click draw initiative again then the tokens appear (but with new initiative).

**Comment by nboughton** [comment]
> Hi @nboughton! Thanks for your patience I know it's been a while since you submitted.
> 
> I'm having some trouble with your links. The images and the learn more page resolves to a 404.
> 
> There's also a small bug with initiative appearing between refreshes. If I have some tokens, add them to initiative, draw initiative and then refresh the page the initiative won't appear. I can see that the extension does remember what tokens had initiative because if I click draw initiative again then the tokens appear (but with new initiative).

Thanks for the response :) I've modified the store.md and rsync'd a new build to my server. I'm not sure what the best way to fix the reload bug is. The initiative list is setup here: https://github.com/nboughton/obr-dragonbane-initiative/blob/main/src/lib/initiativeList.ts

Is there a recommended best practice to ensure the data loads correctly on page reload?

**Comment by nthouliss** [comment]
@mitchemmc is probably best to ask about best practise, especially in regards to the OBR SDK. 

I can see that the list does persist on a re-render. 

I'm still getting a 404 on the image and the icon:

https://nboughton.uk/apps/obr-db-initiative/image.png
https://nboughton.uk/apps/obr-db-initiative/cards.svg

**Comment by nboughton** [comment]
> @mitchemmc is probably best to ask about best practise, especially in regards to the OBR SDK.
> 
> I can see that the list does persist on a re-render.
> 
> I'm still getting a 404 on the image and the icon:
> 
> https://nboughton.uk/apps/obr-db-initiative/image.png https://nboughton.uk/apps/obr-db-initiative/cards.svg

Those links are pointing to the wrong path (mistake on my part), they are fixed in the current version of the store.md that's linked in the pull request.

**Comment by nthouliss** [comment]
> Those links are pointing to the wrong path (mistake on my part), they are fixed in the current version of the store.md that's linked in the pull request.

Those links are still not working in the store page that I am checking. 

https://nboughton.uk/apps/obr-db-initiative/image.png
https://nboughton.uk/apps/obr-db-initiative/cards.svg

**Comment by nboughton** [comment]
Hi Nicola,
Not sure what you mean, if I wget the store.md link: https://nboughton.uk/apps/obr-dragonbane-initiative/store.md

And then view it in VSCode or Obsidian those links are working. The problem is that the original links in the file were wrong as all the content falls under the /apps/obr/dragonbane-initiative/ path and not /apps/obr-db-initiative/

**Review by nthouliss — APPROVED** [review]

**Comment by nthouliss** [comment]
All good! I should have clarified, thanks for your patience as well :)

**Pull request merged**
